// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Website.Repository.Concrete.EntityFramework;

namespace Website.Migrations
{
    [DbContext(typeof(WebsiteContext))]
    partial class WebsiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Website.Entity.Ayar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Eposta");

                    b.Property<string>("FabrikaAdres");

                    b.Property<string>("Instagram");

                    b.Property<string>("Linkedin");

                    b.Property<string>("OfisAdres");

                    b.Property<string>("SiteAciklama");

                    b.Property<string>("SiteBaslik");

                    b.Property<string>("SiteEtiket");

                    b.Property<string>("SiteLogo");

                    b.Property<string>("SiteSlogan");

                    b.Property<string>("SiteUrl");

                    b.Property<string>("Telefon");

                    b.Property<string>("Twitter");

                    b.Property<string>("Youtube");

                    b.HasKey("Id");

                    b.ToTable("Ayarlar");
                });

            modelBuilder.Entity("Website.Entity.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Baslik")
                        .IsRequired();

                    b.Property<string>("Dil")
                        .IsRequired();

                    b.Property<string>("Icerik")
                        .IsRequired();

                    b.Property<int>("KategoriId");

                    b.Property<DateTime>("OlusturulmaTarihi");

                    b.Property<string>("OneCikanGorsel");

                    b.Property<string>("Yazar");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Bloglar");
                });

            modelBuilder.Entity("Website.Entity.Etiket", b =>
                {
                    b.Property<int>("EtiketId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi");

                    b.Property<int?>("BlogId");

                    b.Property<string>("Dil");

                    b.HasKey("EtiketId");

                    b.HasIndex("BlogId");

                    b.ToTable("Etiketler");
                });

            modelBuilder.Entity("Website.Entity.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi")
                        .IsRequired();

                    b.Property<string>("Dil")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("Website.Entity.Resim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi")
                        .IsRequired();

                    b.Property<DateTime>("OlusturulmaTarihi");

                    b.Property<string>("ResimYolu");

                    b.HasKey("Id");

                    b.ToTable("Resimler");
                });

            modelBuilder.Entity("Website.Entity.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aciklama1");

                    b.Property<string>("Aciklama2");

                    b.Property<string>("Aciklama3");

                    b.Property<DateTime>("OlusturulmaTarihi");

                    b.Property<string>("Resim")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Sliderlar");
                });

            modelBuilder.Entity("Website.Entity.SSS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cevap")
                        .IsRequired();

                    b.Property<string>("Dil")
                        .IsRequired();

                    b.Property<DateTime>("OlusturulmaTarihi");

                    b.Property<string>("Soru")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SSSler");
                });

            modelBuilder.Entity("Website.Entity.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aciklama");

                    b.Property<string>("Adi");

                    b.Property<double>("Agirligi");

                    b.Property<double>("Boyu");

                    b.Property<string>("Brosur");

                    b.Property<double>("Capi");

                    b.Property<string>("Dil")
                        .IsRequired();

                    b.Property<int>("DolumHacimi");

                    b.Property<string>("KafaTipi");

                    b.Property<string>("Kodu");

                    b.Property<string>("OneCikanGorsel");

                    b.Property<int>("PaletAgirligi");

                    b.Property<int>("PaletIcAdedi");

                    b.Property<int>("PaletSiraSayisi");

                    b.Property<int>("PaletYuksekligi");

                    b.Property<int>("SilmeHacimi");

                    b.Property<int>("SiraNo");

                    b.Property<int>("TavaUrunAdedi");

                    b.Property<int>("UrunGrupId");

                    b.HasKey("Id");

                    b.HasIndex("UrunGrupId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("Website.Entity.UrunGrup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aciklama");

                    b.Property<string>("Adi")
                        .IsRequired();

                    b.Property<string>("Dil")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("UrunGruplar");
                });

            modelBuilder.Entity("Website.Entity.UrunResim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi")
                        .IsRequired();

                    b.Property<DateTime>("OlusturulmaTarihi");

                    b.Property<int?>("UrunId");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("UrunResimler");
                });

            modelBuilder.Entity("Website.Entity.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi")
                        .IsRequired();

                    b.Property<string>("Link");

                    b.HasKey("Id");

                    b.ToTable("Videolar");
                });

            modelBuilder.Entity("Website.Entity.Yazi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Baslik")
                        .IsRequired();

                    b.Property<string>("Dil")
                        .IsRequired();

                    b.Property<string>("Icerik")
                        .IsRequired();

                    b.Property<DateTime>("OlusturulmaTarihi");

                    b.Property<string>("Yazar");

                    b.HasKey("Id");

                    b.ToTable("Yazilar");
                });

            modelBuilder.Entity("Website.Entity.Blog", b =>
                {
                    b.HasOne("Website.Entity.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Website.Entity.Etiket", b =>
                {
                    b.HasOne("Website.Entity.Blog")
                        .WithMany("Etiketler")
                        .HasForeignKey("BlogId");
                });

            modelBuilder.Entity("Website.Entity.Urun", b =>
                {
                    b.HasOne("Website.Entity.UrunGrup", "UrunGrup")
                        .WithMany()
                        .HasForeignKey("UrunGrupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Website.Entity.UrunResim", b =>
                {
                    b.HasOne("Website.Entity.Urun")
                        .WithMany("UrunResimler")
                        .HasForeignKey("UrunId");
                });
#pragma warning restore 612, 618
        }
    }
}
